### ISSUE TITLE
Add ability to toggle applied colors

### ISSUE THREAD

**Issue by benlammers** [flaming-cl/editorjs-text-color-plugin#10]
### Current Behaviour

For text color once color is applied you can change the color to another color provided by the tool but you can not remove the applied styles to let the text inherit the CSS color property again.

Similar for the marker once a background is applied there is no way to fully remove it, current solution is often to set the background to white or whatever the parent element's background is.

### Desired Behaviour

Allow ability to toggle these styles by clicking their icon on the toolbar to allow the text to return to their default styles. Similar to how the default Bold inline tool works

**Comment by flaming-cl** [comment]
Great suggestion! I took a look at the Bold inline tool, and found this feature is good to have. I'll update it in the next version of the plugin. Thanks!

**Comment by benlammers** [comment]
Awesome! Thanks so much!

**Comment by flaming-cl** [comment]
@benlammers this feature is supported in the latest version of this plugin.
