### ISSUE TITLE
Reset bg-color don't work 

### ISSUE THREAD

**Issue by Orynik** [flaming-cl/editorjs-text-color-plugin#12]
When set #fff for fonts work fine (color style just remove and text inherit default color page), but on marker it doesn't for like that (on marker just set bg-color: #fff) 

I guess in this tool need reset button for clear style (font setting have that mechanics, but not bg) or, at least, styles should reset on repeat click on same color

Using config:

...
        Marker: {
          class: TextColorPicker,
          config: {
            colorCollections: [
              '#ffffff', '#000000', '#e60000', '#ff9900',
              '#ffff00', '#008a00', '#0066cc', '#9933ff',
              '#bbbbbb', '#f06666', '#ffc266', '#ffff66',
              '#66b966', '#66a3e0', '#c285ff', '#888888',
              '#a10000', '#b26b00', '#b2b200', '#006100',
              '#0047b2', '#6b24b2', '#444444', '#5c0000',
              '#663d00', '#666600', '#003700', '#002966',
              '#3d1466'
            ],
            defaultColor: '',
            type: 'marker'
          }
        },
        Color: {
          class: TextColorPicker,
          config: {
            /* TODO: #ffffff - значение по умолчанию, не конфликтует
            * темной и светлой темой
            * */
            colorCollections: [
              '#ffffff', '#000000', '#e60000', '#ff9900',
              '#ffff00', '#008a00', '#0066cc', '#9933ff',
              '#bbbbbb', '#f06666', '#ffc266', '#ffff66',
              '#66b966', '#66a3e0', '#c285ff', '#888888',
              '#a10000', '#b26b00', '#b2b200', '#006100',
              '#0047b2', '#6b24b2', '#444444', '#5c0000',
              '#663d00', '#666600', '#003700', '#002966',
              '#3d1466'
            ],
.....

**Comment by flaming-cl** [comment]
Thanks for reporting the issue. 
Currently, I can not reproduce it through this sample website (built with an older version of Editor.js): https://flaming-cl.github.io/editorPlugin/  Not sure if this is a result of version conflict or I do not follow the right method to reproduce the problem.
Do you mind to provide your current version of Editor.js?

**Comment by Orynik** [comment]
I guess no, i use editojs 2.25
Just try set any color/background color on text and then reset on normaly state (w/o color attribute, not a black), i can't do it

Maybe i misstaken and doesn't saw same solution on readme.

**Comment by flaming-cl** [comment]
@Orynik Thanks for following up. Do you mind to provide more information about this issue following a template like this?

### Issue Title
Clicking on "Security Page" navigates back to "Security Page"

### Device
PC or Mobile

### Operating System
Windows 10 or Mac 

### Browser
Microsoft Edge or Chrome or IE

### How To Reproduce
Steps to reproduce the behavior:

Go to 'https://flaming-cl.github.io/editorPlugin/'
Click on marker color A
Click on marker color B

### Actual Result with Screenshot


### Expected result

**Comment by Orynik** [comment]
@flaming-cl i'll try

### Editorjs Version
2.25

### Issue Title
Marker: Background color can not be reset

### Device
PC

### Operating System
Ubuntu 22.04 LTS

### Browser
Chrome/Firefox

### How To Reproduce
Steps to reproduce the behavior:

Go to 'https://flaming-cl.github.io/editorPlugin/'
Click on marker color Blue
Click on marker same color

### Actual Result with Screenshot
Text color not changed 
![image](https://user-images.githubusercontent.com/19516486/213331167-9298b267-079c-4e0e-a0c8-ab6dcc1a08b4.png)

### Expected result
Text color will reset on default state (w/o color attributte)

**Comment by flaming-cl** [comment]
Thanks! I think I understand this issue now. 
You want to clean the marker/text color by a second click on the same color, right?

**Comment by Orynik** [comment]
Yep, that's right.

**Comment by flaming-cl** [comment]
This issue is similar to https://github.com/flaming-cl/editorjs-text-color-plugin/issues/10
One solution is to make the text color plugin like the bold plugin provided by editor.js.
This feature will be added in the next version of the plugin.
