### ISSUE TITLE
[Bug] Popover change type blocks doesnt't hide when we click on color/marker select block

### ISSUE THREAD

**Issue by Orynik** [flaming-cl/editorjs-text-color-plugin#17]
### Editorjs Version
2.25

### Issue Title
Popovers: Popover change type blocks don't hide when we click on color/marker select block

### Device
PC

### Operating System
Ubuntu 22.04 LTS

### Browser
Chrome/Firefox

### How To Reproduce

Go to 'https://flaming-cl.github.io/editorPlugin/'
Click on 'Convert to'
Click on 'Change text/marker color'

### Actual Result with Screenshot
Popover doesn't hide
![image](https://user-images.githubusercontent.com/19516486/214201318-d8f66a0c-8021-4802-8149-66504c49ed69.png)

### Expected result
Popover "Convert to" hide, like a color/marker popover select

**Comment by flaming-cl** [comment]
Hi, it's fixed in V2.0.2 now. It can be tested here https://flaming-cl.github.io/editorPlugin/
