### ISSUE TITLE
Allow selecting any colour

### ISSUE THREAD

**Issue by AlecRust** [flaming-cl/editorjs-text-color-plugin#5]
Have you considered using the browser's native colour picker, to allow selection of any colour?

i.e. if enabled, an extra item could appear in the list of colours in the picker. When clicked it opens the native colour picker:

![image](https://user-images.githubusercontent.com/247634/160377483-6935e567-b543-4ebb-b1c0-76604456534e.png)

The icon on the extra item could explain it's for "any colour" by having a rainbow effect e.g.

![image](https://user-images.githubusercontent.com/247634/160377363-6a11a843-c8ed-495f-b759-dd46c27f2dce.png)

If you don't like the idea of the native picker, it could even provide just a text box to provide a custom colour.

**Comment by flaming-cl** [comment]
Hi, thanks for your suggestions. 
The idea of adding a native color picker is what I am thinking about as well.
It will be added in the next release.

**Comment by ruess** [comment]
@flaming-cl  - great to hear you're thinking of adding a color-picker to the next release! This would be awesome. Loving the tool so far - thanks!

**Comment by HaoCherHong** [comment]
@flaming-cl @ruess 
Just make an PR(#6) for this feature, check it out.

**Comment by ruess** [comment]
That's fantastic thank you!
