### ISSUE TITLE
Font Color markup is not exported on save

### ISSUE THREAD

**Issue by Abdul-develop** [flaming-cl/editorjs-text-color-plugin#7]
Versions:.
vue@2.6.10
node v12.18.2
 "@editorjs/editorjs": "^2.23.2",
 
Html :
////////////
`<div class="ce-paragraph cdx-block" data-placeholder="Start typing here ... Press Tab button for options" contenteditable="true">Testing <font color="red">font color</font> in editor js</div>`
//////////////
![image](https://user-images.githubusercontent.com/56625427/168523012-c9501ff5-998e-4803-94da-52b2d0ff8e4f.png)
![4225761](https://user-images.githubusercontent.com/56625427/168523502-4e433951-8c84-4f65-810b-794c5b737cd5.png)

**Comment by flaming-cl** [comment]
My environment: 
@editorjs/editorjs: "^2.23.2     
editorjs-text-color-plugin: "^1.13.1"      
Hi, it seems that the latest version of the color plugin works okay on editorjs@2.23.2.   
![Screen Shot 2022-05-16 at 3 27 21 PM](https://user-images.githubusercontent.com/51183663/168540782-7d3e474a-fc4c-4969-9ddf-ddb6fb71c2e6.png)

Do you mind to provide more details about how this happens?
Many thanks!!

**Comment by Abdul-develop** [comment]
Okay ,Thank you.

My environment:
@editorjs/editorjs: "^2.23.2
editorjs-text-color-plugin: "^1.13.1"
=======================


Please check it step wise:-
const ColorPlugin = require('editorjs-text-color-plugin');

==================
config Color: {
                        class: ColorPlugin, // if load from CDN, please try: window.ColorPlugin
                        config: {
                           colorCollections: \['#9C27B0','#673AB7','#3F51B5','#0070FF','#03A9F4','#00BCD4','#4CAF50','#8BC34A','#CDDC39', '#FFF'],
                           defaultColor: '#9C27B0',
                           type: 'text', 
                        }     
                      },
=================================================
![image](https://user-images.githubusercontent.com/56625427/169610068-8d436cda-b3f6-47e1-9070-42ddb395dadc.png)

**Comment by flaming-cl** [comment]
Hi, I would really like to help, but sorry that it may not be very straightforward for me to spot why this shows up, coz this problem can not be shown with the code I've already got.

But I feel that if the text can be successfully colored, the answer may lie in how/when you store your block data. Maybe pick up a different timing to store the data block will solve this problem?

**Comment by Abdul-develop** [comment]
okay Sure, thank you

**Comment by Abdul-develop** [comment]
<template>
    <form method="post">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group text-right">
                     <img v-if="loader" src="/images/loader_small.gif">
                     <small v-if="!loader && saveText != ''">{{ saveText }}</small>
                    <button class="btn btn-dark" type="button"  @click="updateCourseAndBack()" :disabled="courseId <= 0 && loader == true">Save</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-custom">Add Course Overview</div>
                    <div class="card-body">
                        <div class="form-group">
                            <editor v-if="loadEditor" ref="editor" :config="config" />
                        </div>
                        <hr>

                    </div>
                </div>
            </div>
        </div>
    </form>
</template>
<script>

import Header from '@editorjs/header';
import List from '@editorjs/list';
import CodeTool from '@editorjs/code'
import Embed from '@editorjs/embed'
import Checklist from '@editorjs/checklist'
import Paragraph from '@editorjs/paragraph'
import Marker from '@editorjs/marker'
import RawTool from '@editorjs/raw'
import Quote from '@editorjs/quote'
import InlineCode from '@editorjs/inline-code'
import ImageTool from '@editorjs/image';
import BaseAttachesTool from '@editorjs/attaches';
const FontSize = require('editorjs-inline-font-size-tool');
const ColorPlugin = require('editorjs-text-color-plugin');
const AlignmentTuneTool = require('editorjs-text-alignment-blocktune');
const FontFamily = require('editorjs-inline-font-family-tool');

/**
 * Module for file uploading.
 */
import ajax from '@codexteam/ajax';



class Uploader {
    /**
     * @param {Object} config
     * @param {function} onUpload - callback for successful file upload
     * @param {function} onError - callback for uploading errors
     */
    constructor({config, onUpload, onError}) {
        this.config = config;
        this.onUpload = onUpload;
        this.onError = onError;
    }

    /**
     * Handle clicks on the upload file button
     * @fires ajax.transport()
     * @param {function} onPreview - callback fired when preview is ready
     */
    uploadSelectedFile({onPreview}) {
        ajax.transport({
            url: this.config.endpoint || '',
            accept: this.config.types || '*',
            data: this.config.additionalRequestData || {},
            headers: this.config.additionalRequestHeaders || {},
            beforeSend: () => onPreview(),
            fieldName: this.config.field || 'file'
        }).then((response) => {
            this.onUpload(response);
        }).catch((error) => {
            const message = (error && error.message) ? error.message : this.config.errorMessage || 'File upload failed';

            this.onError(message);
        });
    }
}

class AttachesTool extends BaseAttachesTool{
    /**
     * @param {AttachesToolData} data
     * @param {Object} config
     * @param {API} api
     */
    constructor({ data, config, api }) {
        super({ data: data, config: config, api: api });

        super.uploader = new Uploader({
            config: config,
            onUpload: (response) => super.onUpload(response),
            onError: (error) => super.uploadingFailed(error)
        });
    }
}

export default {
    name: 'CourseOverviewEditor',
    data() {
        return {
            loadEditor: false,
            loader: true,
            saveText: '',
            cancelSource: null,
            courseId: Number(this.$route.params.id),
            course: {
                id: '',
                status: 'draft'
            },
            config: {
                placeholder: 'Start typing here ... Press Tab button for options',
                autofocus: true,
                tools:{
                    header: {
                        class: Header,
                        tunes: ['alignmentTune'],
                        config: {
                            placeholder: 'Heading',
                            levels: [2, 3, 4],
                            defaultLevel: 3,
                        }
                    },

                    embed: {
                        class: Embed,
                        inlineToolbar: true,
                        config: {
                            services: {
                                youtube: true,
                            }
                        }
                    },

                     Color: {
                        class: ColorPlugin, // if load from CDN, please try: window.ColorPlugin
                        config: {
                           colorCollections: ['#EC7878','#9C27B0','#673AB7','#3F51B5','#0070FF','#03A9F4','#00BCD4','#4CAF50','#8BC34A','#CDDC39', '#FFF'], 
                            defaultColor: '#FF1300',
                             type: 'text',
                        }     
                      },
                    Marker: {
                        class: ColorPlugin, // if load from CDN, please try: window.ColorPlugin
                        config: {
                           defaultColor: '#FFBF00',
                           type: 'marker', 
                        }       npm au
                      },

                    fontSize: FontSize,
                    fontFamily: FontFamily,
                    attaches: {
                        class: AttachesTool,
                        config: {
                            endpoint: '/api/lessons/attachUpload',
                            additionalRequestHeaders: {'Authorization': 'Bearer ' + localStorage.getItem("api_token")},
                            additionalRequestData: {
                                object_type: 'course/editor/attachment',
                                object_id: Number(this.$route.params.id),
                            }
                        }
                    },
                    code: {
                        class: CodeTool
                    },
                    list: {
                        class: List,
                        inlineToolbar: true,
                        tunes: ['alignmentTune'],
                    },
                    paragraph: {
                        class: Paragraph,                        
                        tunes: ['alignmentTune'],
                         inlineToolbar: true
                          },                           
                    image: {
                        class: ImageTool,                        
                        tunes: ['alignmentTune'],
                        config: {
                            endpoints: {
                                byFile: '/api/lessons/imageUpload', // Your backend file uploader endpoint
                                byUrl: 'http://localhost:8008/fetchUrl', // Your endpoint that provides uploading by Url
                            },
                            additionalRequestData: {
                                object_type: 'course/editor/image',
                                media_type: 'image',
                                object_id: Number(this.$route.params.id),
                                user_name: this.$store.state.name
                            },
                            additionalRequestHeaders: {'Authorization': 'Bearer ' + localStorage.getItem("api_token")}
                        }
                    },


                    checklist: {
                        class: Checklist,
                        tunes: ['alignmentTune'],
                    },
                    Marker: {
                        class: Marker,
                        shortcut: 'CMD+SHIFT+M',
                    },

                    raw: RawTool,
                    quote: {
                        class: Quote,
                        inlineToolbar: true,
                        shortcut: 'CMD+SHIFT+O',
                        config: {
                        quotePlaceholder: 'Enter a quote',
                        captionPlaceholder: 'Quote\'s author',
                        },
                    },
                    inlineCode: {
                        class: InlineCode,
                        shortcut: 'CMD+SHIFT+M',
                    },
                    alignmentTune: {
                      class:AlignmentTuneTool,
                      config:{
                        default: "left"        
                      },
                    }

                },
                onReady: () => {
                    console.log('on ready')
                },
                onChange: (args) => {
                    
                    args.saver.save().then((outputData) => {
                       // console.log('Article data: ', outputData)
                        this.saveData(outputData);
                    }).catch((error) => {
                        console.log('Saving failed: ', error)
                    });

                },

                data: {
                    //"time": 1591362820044,
                    blocks: []
                }

            }
        }
    },
    methods: {
        updateBlock: _.debounce(function (res) {
             var blocks = res.data.data.description;
             if(blocks == null) blocks = [{type: 'paragraph', data: {}}];
             this.config.data.blocks = blocks;
            this.loadEditor = true;
        }, 0),

         saveData: _.debounce(function (response) {
            this.course.description = response.blocks;
            console.log("course data", this.course);
            this.updateCourse();
        }, 2000),

        cancelUpdate () {
            if (this.cancelSource) {
                this.cancelSource.cancel('Start new update, stop active update');
                console.log('cancel request done');
            }
        },
        hideMessage: _.debounce(function () {
            this.saveText = '';
        }, 3000),
        updateCourse(){
            this.loader = true;
            let form = this.course;
            form._method = 'PUT';
            form.courseId = this.courseId;
            this.cancelUpdate();
            this.cancelSource = this.axios.CancelToken.source();
            this.axios.post('courses/update', form, {
                cancelToken: this.cancelSource.token })
            .then(res => {
                this.loader = false;
                this.saveText = 'Data saved..';
                this.hideMessage();
            }).catch(error => {
                this.loader = false;
                this.saveText = 'Data saved failed..';
                this.hideMessage();
            })
        },
        updateCourseAndBack(){
            this.updateCourse();
            setTimeout(() => this.$router.push({path: `/creator/courses/course/${this.courseId}`}), 1500);
        }
    },
    mounted() {
        if(this.courseId > 0){
            this.loader = true;
             this.axios.get('courses/edit/' + this.courseId)
            .then(res => {
                this.loader = false;
                this.course = res.data.data;
                this.updateBlock(res);
            })
            .catch(error => {
                this.loader = false;
                this.$toast.error("something went wrong");
            })
        }
    }
}
</script>

**Comment by Abdul-develop** [comment]
<template>
    <form method="post">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group text-right">
                     <img v-if="loader" src="/images/loader_small.gif">
                     <small v-if="!loader && saveText != ''">{{ saveText }}</small>
                    <button class="btn btn-dark" type="button"  @click="updateCourseAndBack()" :disabled="courseId <= 0 && loader == true">Save</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-custom">Add Course Overview</div>
                    <div class="card-body">
                        <div class="form-group">
                            <editor v-if="loadEditor" ref="editor" :config="config" />
                        </div>
                        <hr>

                    </div>
                </div>
            </div>
        </div>
    </form>
</template>
<script>

import Header from '@editorjs/header';
import List from '@editorjs/list';
import CodeTool from '@editorjs/code'
import Embed from '@editorjs/embed'
import Checklist from '@editorjs/checklist'
import Paragraph from '@editorjs/paragraph'
import Marker from '@editorjs/marker'
import RawTool from '@editorjs/raw'
import Quote from '@editorjs/quote'
import InlineCode from '@editorjs/inline-code'
import ImageTool from '@editorjs/image';
import BaseAttachesTool from '@editorjs/attaches';
const FontSize = require('editorjs-inline-font-size-tool');
const ColorPlugin = require('editorjs-text-color-plugin');
const AlignmentTuneTool = require('editorjs-text-alignment-blocktune');
const FontFamily = require('editorjs-inline-font-family-tool');

/**
 * Module for file uploading.
 */
import ajax from '@codexteam/ajax';



class Uploader {
    /**
     * @param {Object} config
     * @param {function} onUpload - callback for successful file upload
     * @param {function} onError - callback for uploading errors
     */
    constructor({config, onUpload, onError}) {
        this.config = config;
        this.onUpload = onUpload;
        this.onError = onError;
    }

    /**
     * Handle clicks on the upload file button
     * @fires ajax.transport()
     * @param {function} onPreview - callback fired when preview is ready
     */
    uploadSelectedFile({onPreview}) {
        ajax.transport({
            url: this.config.endpoint || '',
            accept: this.config.types || '*',
            data: this.config.additionalRequestData || {},
            headers: this.config.additionalRequestHeaders || {},
            beforeSend: () => onPreview(),
            fieldName: this.config.field || 'file'
        }).then((response) => {
            this.onUpload(response);
        }).catch((error) => {
            const message = (error && error.message) ? error.message : this.config.errorMessage || 'File upload failed';

            this.onError(message);
        });
    }
}

class AttachesTool extends BaseAttachesTool{
    /**
     * @param {AttachesToolData} data
     * @param {Object} config
     * @param {API} api
     */
    constructor({ data, config, api }) {
        super({ data: data, config: config, api: api });

        super.uploader = new Uploader({
            config: config,
            onUpload: (response) => super.onUpload(response),
            onError: (error) => super.uploadingFailed(error)
        });
    }
}

export default {
    name: 'CourseOverviewEditor',
    data() {
        return {
            loadEditor: false,
            loader: true,
            saveText: '',
            cancelSource: null,
            courseId: Number(this.$route.params.id),
            course: {
                id: '',
                status: 'draft'
            },
            config: {
                placeholder: 'Start typing here ... Press Tab button for options',
                autofocus: true,
                tools:{
                    header: {
                        class: Header,
                        tunes: ['alignmentTune'],
                        config: {
                            placeholder: 'Heading',
                            levels: [2, 3, 4],
                            defaultLevel: 3,
                        }
                    },

                    embed: {
                        class: Embed,
                        inlineToolbar: true,
                        config: {
                            services: {
                                youtube: true,
                            }
                        }
                    },

                     Color: {
                        class: ColorPlugin, // if load from CDN, please try: window.ColorPlugin
                        config: {
                           colorCollections: ['#EC7878','#9C27B0','#673AB7','#3F51B5','#0070FF','#03A9F4','#00BCD4','#4CAF50','#8BC34A','#CDDC39', '#FFF'], 
                            defaultColor: '#FF1300',
                             type: 'text',
                        }     
                      },
                    Marker: {
                        class: ColorPlugin, // if load from CDN, please try: window.ColorPlugin
                        config: {
                           defaultColor: '#FFBF00',
                           type: 'marker', 
                        }       npm au
                      },

                    fontSize: FontSize,
                    fontFamily: FontFamily,
                    attaches: {
                        class: AttachesTool,
                        config: {
                            endpoint: '/api/lessons/attachUpload',
                            additionalRequestHeaders: {'Authorization': 'Bearer ' + localStorage.getItem("api_token")},
                            additionalRequestData: {
                                object_type: 'course/editor/attachment',
                                object_id: Number(this.$route.params.id),
                            }
                        }
                    },
                    code: {
                        class: CodeTool
                    },
                    list: {
                        class: List,
                        inlineToolbar: true,
                        tunes: ['alignmentTune'],
                    },
                    paragraph: {
                        class: Paragraph,                        
                        tunes: ['alignmentTune'],
                         inlineToolbar: true
                          },                           
                    image: {
                        class: ImageTool,                        
                        tunes: ['alignmentTune'],
                        config: {
                            endpoints: {
                                byFile: '/api/lessons/imageUpload', // Your backend file uploader endpoint
                                byUrl: 'http://localhost:8008/fetchUrl', // Your endpoint that provides uploading by Url
                            },
                            additionalRequestData: {
                                object_type: 'course/editor/image',
                                media_type: 'image',
                                object_id: Number(this.$route.params.id),
                                user_name: this.$store.state.name
                            },
                            additionalRequestHeaders: {'Authorization': 'Bearer ' + localStorage.getItem("api_token")}
                        }
                    },


                    checklist: {
                        class: Checklist,
                        tunes: ['alignmentTune'],
                    },
                    Marker: {
                        class: Marker,
                        shortcut: 'CMD+SHIFT+M',
                    },

                    raw: RawTool,
                    quote: {
                        class: Quote,
                        inlineToolbar: true,
                        shortcut: 'CMD+SHIFT+O',
                        config: {
                        quotePlaceholder: 'Enter a quote',
                        captionPlaceholder: 'Quote\'s author',
                        },
                    },
                    inlineCode: {
                        class: InlineCode,
                        shortcut: 'CMD+SHIFT+M',
                    },
                    alignmentTune: {
                      class:AlignmentTuneTool,
                      config:{
                        default: "left"        
                      },
                    }

                },
                onReady: () => {
                    console.log('on ready')
                },
                onChange: (args) => {
                    
                    args.saver.save().then((outputData) => {
                       // console.log('Article data: ', outputData)
                        this.saveData(outputData);
                    }).catch((error) => {
                        console.log('Saving failed: ', error)
                    });

                },

                data: {
                    //"time": 1591362820044,
                    blocks: []
                }

            }
        }
    },
    methods: {
        updateBlock: _.debounce(function (res) {
             var blocks = res.data.data.description;
             if(blocks == null) blocks = [{type: 'paragraph', data: {}}];
             this.config.data.blocks = blocks;
            this.loadEditor = true;
        }, 0),

         saveData: _.debounce(function (response) {
            this.course.description = response.blocks;
            console.log("course data", this.course);
            this.updateCourse();
        }, 2000),

        cancelUpdate () {
            if (this.cancelSource) {
                this.cancelSource.cancel('Start new update, stop active update');
                console.log('cancel request done');
            }
        },
        hideMessage: _.debounce(function () {
            this.saveText = '';
        }, 3000),
        updateCourse(){
            this.loader = true;
            let form = this.course;
            form._method = 'PUT';
            form.courseId = this.courseId;
            this.cancelUpdate();
            this.cancelSource = this.axios.CancelToken.source();
            this.axios.post('/', form, {
                cancelToken: this.cancelSource.token })
            .then(res => {
                this.loader = false;
                this.saveText = 'Data saved..';
                this.hideMessage();
            }).catch(error => {
                this.loader = false;
                this.saveText = 'Data saved failed..';
                this.hideMessage();
            })
        },
        updateCourseAndBack(){
            this.updateCourse();
            setTimeout(() => this.$router.push({path: `/`}), 1500);
        }
    },
    mounted() {
        if(this.courseId > 0){
            this.loader = true;
             this.axios.get('')
            .then(res => {
                this.loader = false;
                this.course = res.data.data;
                this.updateBlock(res);
            })
            .catch(error => {
                this.loader = false;
                this.$toast.error("something went wrong");
            })
        }
    }
}
</script>

**Comment by Abdul-develop** [comment]
any updates ,about this issue?
