### ISSUE TITLE
Font color is not working properly with Font size And Font Family Plugins

### ISSUE THREAD

**Issue by Abdul-develop** [flaming-cl/editorjs-text-color-plugin#8]
Versions:
 "core-js": "~3.6.4",
    "editorjs-inline-font-family-tool": "^1.0.4",
    "editorjs-inline-font-size-tool": "^1.0.1",
    "editorjs-text-color-plugin": "^1.12.1",
 Issue:
When Font size And Font Family Plugins  are active then Font color is not passing color to json array during saving/storing process ,

**Comment by flaming-cl** [comment]
Sorry, this problem does not show up when I am using all the libraries mentioned above, with editor.js ^2.23.2".
![Screen Shot 2022-07-18 at 2 42 31 PM](https://user-images.githubusercontent.com/51183663/179580652-c017b04c-fc6a-4223-860a-a30f1d6a92d6.png)
![Screen Shot 2022-07-18 at 2 38 05 PM](https://user-images.githubusercontent.com/51183663/179580688-0a8d99fa-ee61-4314-afcc-ecb3cd831032.png)
![Screen Shot 2022-07-18 at 2 37 49 PM](https://user-images.githubusercontent.com/51183663/179580711-0ba3eb03-6a13-47f0-b46d-7f7f877904ef.png)

May need more users to report similar problems with more detailed descriptions.
Thanks!

**Comment by Abdul-develop** [comment]
okay Thank you for quick response,can You Please share latest stable version of these plugins which have no conflict with each an other

**Comment by Abdul-develop** [comment]
I am using "vue-editor-js": "^2.0.2", Please share solution for vue editor

**Comment by flaming-cl** [comment]
Hi, I found this plugin works well when adopting editorjs with vuejs. You get a problem with editorjs state exporting, may because the "vue-editor-js" library only supports a limited number of plugins.

**Comment by AntonMoldakov** [comment]
I use
```
  "editorjs-inline-font-size-tool": "^1.0.1",
   "editorjs-text-color-plugin": "^1.13.1",
```
And it doesn't work
` 
 Color: {
          class: ColorPlugin,
          config: {
            customPicker: true,
            type: 'text',
          },
    },
 fontSize: FontSize,
`
`"type":"paragraph","data":{"text":"<font size=\"5\">Text</font>"`

But this works for me
`  fontSize: FontSize,
    Color: {
          class: ColorPlugin,
          config: {
            customPicker: true,
            type: 'text',
          },
    },
`
`"type":"paragraph","data":{"text":"<font size=\"5\" color=\"#ff1300\">Text</font>"}`

**Comment by flaming-cl** [comment]
> I use
> 
> ```
>   "editorjs-inline-font-size-tool": "^1.0.1",
>   "editorjs-text-color-plugin": "^1.13.1",
> ```
> 
> And it doesn't work ` Color: { class: ColorPlugin, config: { customPicker: true, type: 'text', }, }, fontSize: FontSize,` `"type":"paragraph","data":{"text":"<font size=\"5\">Text</font>"`
> 
> But this works for me ` fontSize: FontSize, Color: { class: ColorPlugin, config: { customPicker: true, type: 'text', }, },` `"type":"paragraph","data":{"text":"<font size=\"5\" color=\"#ff1300\">Text</font>"}`

Do you mind to share the FE framework (React/Vue/Angular) you are using?

**Comment by flaming-cl** [comment]
> I use
> 
> ```
>   "editorjs-inline-font-size-tool": "^1.0.1",
>   "editorjs-text-color-plugin": "^1.13.1",
> ```
> 
> And it doesn't work ` Color: { class: ColorPlugin, config: { customPicker: true, type: 'text', }, }, fontSize: FontSize,` `"type":"paragraph","data":{"text":"<font size=\"5\">Text</font>"`
> 
> But this works for me ` fontSize: FontSize, Color: { class: ColorPlugin, config: { customPicker: true, type: 'text', }, },` `"type":"paragraph","data":{"text":"<font size=\"5\" color=\"#ff1300\">Text</font>"}`

This is a workable solution, as the FONT tag output from editorjs-text-color-plugin was **overwrote** by editorjs-inline-font-size-tool. 
#### Reasons in detail:
1. The editorjs-inline-font-size-tool tool only exports "size" and "face" properties from editorjs HTML. 
```
  static get sanitize() {
    return {
      font: {
        size: true,
        face: true
      },
    };
  }
```
2. If you put the font size plugin after the color plugin, "color" property will be omitted by Editor.js when saving editor data.

Solution:
1. A quick solution is to make pull request to "editorjs-inline-font-size-tool" to allow more FONT properties exported by Editor.js. 
> But this may not be an effective solution. As there may be other plugins only exports it properties and 
ignores the others'.

2. A better solution is to make PR to Editor.js.
