### ISSUE TITLE
How can I make the color plugin work on Headers too, not just text?

### ISSUE THREAD

**Issue by Joseph-Azzam** [flaming-cl/editorjs-text-color-plugin#9]

**Comment by flaming-cl** [comment]
Hi, do you mind to provide more details (texts or screenshots will be appreciated) about this issue?
Is that the color plugin is not listed in the toolbar, when you select a piece of text in a heading paragraph?

**Comment by Joseph-Azzam** [comment]
Hi never mind I just fixed it, my bad.
I had the inlineToolbar property set to link only

**Comment by flaming-cl** [comment]
No worries, glad to help
